import { hOAYSDesc } from "./filmDescription.js";
import { geniusDesc } from "./filmDescription.js";
import { papillonDesc } from "./filmDescription.js";
import { thePOTDDesc } from "./filmDescription.js";
import { tCCOBBDesc } from "./filmDescription.js";
import { tWOWSDesc } from "./filmDescription.js";
import { malcolmXDesc } from "./filmDescription.js";
import { theWhaleDesc } from "./filmDescription.js";
import { bloodDiamodDesc } from "./filmDescription.js";
import { fencesDesc } from "./filmDescription.js";
import { greenBookDesc } from "./filmDescription.js";


export const films = [
    {
        id: 1,
        title: "Green book",
        image: "img/green-book.jpg",
        production: 2018,
        rating: "9.0",
        duration: "2mins 30secs",
        description: greenBookDesc,
        billboard: "yes",
        category: "",
        categoryCri: "",
        categoryDoc: "",
        categoryDra: "Drama",
        categoryBio: "Biography",
        categorySci: "",
        categoryFan: "",
        categoryAdv: "Adventure",
        categoryHor: "",
        categoryNSFW: "",
        categoryAni: "",
        categoryWes: "",
        categoryRom: "Romance",
        video: "vid/Green-Book.MP4",
        playVideo: () => { videos.src = "vid/Green-Book.MP4"; 
            myVideo.style.display= "block"; videos.play();
        }
    },
    {
        id: 2,
        title: "Blood diamond",
        image: "img/bloodDiamond2006.jpg",
        production: 2006,
        rating: "9.5",
        duration: "2mins 26secs",
        description: bloodDiamodDesc,
        billboard: "yes",
        category: "Action",
        categoryCri: "Crime",
        categoryDoc: "Documentary",
        categoryDra: "",
        categoryBio: "",
        categorySci: "",
        categoryFan: "",
        categoryAdv: "Adventure",
        categoryHor: "",
        categoryNSFW: "",
        categoryAni: "",
        categoryWes: "",
        categoryRom: "",
        video: "vid/Blood-Diamond.MP4",
        playVideo: () => { videos.src = "vid/Blood-Diamond.MP4"; 
            myVideo.style.display= "block";  videos.play();
        }
    },
    {
        id: 3,
        title: "Fences",
        image: "img/fences.jpg",
        production: 2016,
        rating: "8.0",
        duration: "2mins 26secs",
        description: fencesDesc,
        billboard: "yes",
        category: "",
        categoryCri: "",
        categoryDoc: "",
        categoryDra: "Drama",
        categoryBio: "",
        categorySci: "",
        categoryFan: "Fantasy",
        categoryAdv: "",
        categoryHor: "",
        categoryNSFW: "",
        categoryAni: "",
        categoryWes: "",
        categoryRom: "Romance",
        video: "vid/Fences.MP4",
        playVideo: () => { videos.src = "vid/Fences.MP4";
            myVideo.style.display= "block"; videos.play();
        }
    },
    {
        id: 4,
        title: "Genius",
        image: "img/Genius-2016.jpg",
        production: 2016,
        rating: "8.5",
        duration: "2mins 31secs",
        description: geniusDesc,
        billboard: "yes",
        category: "",
        categoryCri: "",
        categoryDoc: "Documentary",
        categoryDra: "Drama",
        categoryBio: "Biography",
        categorySci: "",
        categoryFan: "",
        categoryAdv: "Adventure",
        categoryHor: "",
        categoryNSFW: "",
        categoryAni: "",
        categoryWes: "",
        categoryRom: "Romance",
        video: "vid/Genius.MP4",
        playVideo: () => { videos.src = "vid/Genius.MP4"; 
            myVideo.style.display= "block"; videos.play(); 
        }
    },
    {
        id: 5,
        title: "Half of a yellow sun",
        image: "img/half-of-a-yellow-sun.jpg",
        production: 2013,
        rating: "8.5",
        duration: "2mins 15secs",
        description: hOAYSDesc,
        billboard: "yes",
        category: "Action",
        categoryCri: "Crime",
        categoryDoc: "Documentary",
        categoryDra: "Drama",
        categoryBio: "Biography",
        categorySci: "",
        categoryFan: "Fantasy",
        categoryAdv: "Adventure",
        categoryHor: "",
        categoryNSFW: "",
        categoryAni: "",
        categoryWes: "",
        categoryRom: "Romance", 
        video: "vid/Half-of-a-Yellow-Sun.MP4",
        playVideo: () => { videos.src = "vid/Half-of-a-Yellow-Sun.MP4"; 
            myVideo.style.display= "block"; videos.play();
        }
    },
    {
        id: 6, 
        title: "The Whale",
        image: "img/theWhale.jpeg",
        production: 2022,
        rating: "9.0",
        duration: "1min 50secs",
        description: theWhaleDesc,
        billboard: "yes",
        category: "",
        categoryCri: "",
        categoryDoc: "",
        categoryDra: "Drama",
        categoryBio: "",
        categorySci: "",
        categoryFan: "Fantasy",
        categoryAdv: "",
        categoryHor: "",
        categoryNSFW: "",
        categoryAni: "",
        categoryWes: "",
        categoryRom: "Romance",
        video: "vid/theWhale.MP4",
        playVideo: () => { videos.src = "vid/theWhale.MP4";
            myVideo.style.display= "block"; videos.play();
        }
    },
    {
        id: 7,
        title: "Papillon",
        image: "img/papillon.jpg",
        production: 2017,
        rating: "8.5",
        duration: "2mins 25secs",
        description: papillonDesc,
        billboard: "yes",
        category: "Action",
        categoryCri: "Crime",
        categoryDoc: "Documentary",
        categoryDra: "Drama",
        categoryBio: "Biography",
        categorySci: "",
        categoryFan: "",
        categoryAdv: "Adventure",
        categoryHor: "",
        categoryNSFW: "",
        categoryAni: "",
        categoryWes: "",
        categoryRom: "",
        video: "vid/Papillon.MP4",
        playVideo: () => { videos.src = "vid/Papillon.MP4";
            myVideo.style.display= "block"; videos.play();
        }
    },
    {
        id: 8,
        title: "Malcolm X",
        image: "img/malcolm-x.jpeg",
        production: 1992,
        rating: "9.0",
        duration: "2mins 45secs",
        description: malcolmXDesc,
        billboard: "yes",
        category: "Action",
        categoryCri: "Crime",
        categoryDoc: "Documentary",
        categoryDra: "Drama",
        categoryBio: "Biography",
        categorySci: "",
        categoryFan: "",
        categoryAdv: "Adventure",
        categoryHor: "",
        categoryNSFW: "",
        categoryAni: "",
        categoryWes: "",
        categoryRom: "",
        video: "vid/Malcolm X.MP4",
        playVideo: () => { videos.src = "vid/Malcolm X.MP4";
            myVideo.style.display= "block"; videos.play();
        }
    },
    {
        id: 9,
        title: "The prince of the desert",
        image: "img/prince-of-the-desert.jpeg",
        production: 2020,
        rating: "8.0",
        duration: "2mins 03secs",
        description: thePOTDDesc,
        billboard: "yes",
        category: "Action",
        categoryCri: "",
        categoryDoc: "Documentary",
        categoryDra: "Drama",
        categoryBio: "",
        categorySci: "",
        categoryFan: "",
        categoryAdv: "Adventure",
        categoryHor: "",
        categoryNSFW: "",
        categoryAni: "",
        categoryWes: "",
        categoryRom: "",
        video: "vid/the-prince-of-the-desert.MP4",
        playVideo: () => { videos.src = "vid/the-prince-of-the-desert.MP4";
            myVideo.style.display= "block"; videos.play();
        }
    },
    {
        id: 10,
        title: "The wolf of wallstreet",
        image: "img/the-wolf-of-wall-street.jpg",
        production: 2013,
        rating: "9.0",
        duration: "2mins 33secs",
        description: tWOWSDesc,
        billboard: "yes",
        category: "",
        categoryCri: "Crime",
        categoryDoc: "Documentary",
        categoryDra: "Drama",
        categoryBio: "Biography",
        categorySci: "",
        categoryFan: "Fantasy",
        categoryAdv: "Adventure",
        categoryHor: "",
        categoryNSFW: "",
        categoryAni: "",
        categoryWes: "",
        categoryRom: "",
        video: "vid/The-wolf-of-wallstreet.MP4",
        playVideo: () => { videos.src = "vid/The-wolf-of-wallstreet.MP4";
            myVideo.style.display= "block"; videos.play();
        }
    },
    {
        id: 11,
        title: "The curious case of  Benjamin Button",
        image: "img/the-curious-case-of-benjamin-button-2008.jpg",
        production: 2008,
        rating: "9.0",
        duration: "2mins 39secs",
        description: tCCOBBDesc,
        billboard: "yes",
        category: "",
        categoryCri: "",
        categoryDoc: "",
        categoryDra: "Drama",
        categoryBio: "",
        categorySci: "SciFi",
        categoryFan: "Fantasy",
        categoryAdv: "Adventure",
        categoryHor: "",
        categoryNSFW: "",
        categoryAni: "",
        categoryWes: "",
        categoryRom: "",
        video: "vid/TheCuriousCaseOfBenjaminButton.MP4",
        playVideo: () => { videos.src = "vid/TheCuriousCaseOfBenjaminButton.MP4";
            myVideo.style.display= "block"; videos.play();
        }
    },
    {
        id: 12,
        title: "Fantastic beasts and where to find them",
        image: "img/Fantastic-beasts-and-where-to-find-them-2017.jpg",
        production: 2017,
        rating: "8.0",
        duration: "2mins 29secs",
        description: "Fantastic beasts and where to find them description",
        category: "Action",
        categoryCri: "Crime",
        categoryDoc: "",
        categoryDra: "Drama",
        categoryBio: "",
        categorySci: "SciFi",
        categoryFan: "Fantasy",
        categoryAdv: "Adventure",
        categoryHor: "Horror",
        categoryNSFW: "",
        categoryAni: "",
        categoryWes: "",
        categoryRom: "Romance",
        video: "vid/TheCuriousCaseOfBenjaminButton.MP4",
        playVideo: () => { videos.src = "vid/TheCuriousCaseOfBenjaminButton.MP4";
            myVideo.style.display= "block"; videos.play();
        }
    },
    {
        id: 13,
        title: "The Accountant",
        image: "img/theAccountant2016.jpeg",
        production: 2016,
        rating: "8.5",
        duration: "2mins 29secs",
        description: "The Accountant description",
        category: "Action",
        categoryCri: "Crime",
        categoryDoc: "",
        categoryDra: "",
        categoryBio: "",
        categorySci: "",
        categoryFan: "",
        categoryAdv: "",
        categoryHor: "",
        categoryNSFW: "",
        categoryAni: "",
        categoryWes: "",
        categoryRom: "",
        video: "vid/TheCuriousCaseOfBenjaminButton.MP4",
        playVideo: () => { videos.src = "vid/TheCuriousCaseOfBenjaminButton.MP4";
            myVideo.style.display= "block"; videos.play();
        }
    },
    {
        id: 14,
        title: "Mad Max",
        image: "img/Mad-Max.jpg",
        production: 2015,
        rating: "9.0",
        duration: "2mins 29secs",
        description: "Mad Max description",
        category: "Action",
        categoryCri: "",
        categoryDoc: "",
        categoryDra: "",
        categoryBio: "",
        categorySci: "SciFi",
        categoryFan: "Fantasy",
        categoryAdv: "Adventure",
        categoryHor: "",
        categoryNSFW: "",
        categoryAni: "",
        categoryWes: "",
        categoryRom: "",
        video: "vid/TheCuriousCaseOfBenjaminButton.MP4",
        playVideo: () => { videos.src = "vid/TheCuriousCaseOfBenjaminButton.MP4";
            myVideo.style.display= "block"; videos.play();
        }
    },
    {
        id: 15,
        title: "Norman",
        image: "img/Norman2016.png",
        production: 2016,
        rating: "8.0",
        duration: "2mins 29secs",
        description: "Norman description",
        category: "",
        categoryCri: "",
        categoryDoc: "",
        categoryDra: "Drama",
        categoryBio: "",
        categorySci: "",
        categoryFan: "Fantasy",
        categoryAdv: "",
        categoryHor: "",
        categoryNSFW: "",
        categoryAni: "",
        categoryWes: "",
        categoryRom: "",
        video: "vid/TheCuriousCaseOfBenjaminButton.MP4",
        playVideo: () => { videos.src = "vid/TheCuriousCaseOfBenjaminButton.MP4";
            myVideo.style.display= "block"; videos.play();
        }
    },
    {
        id: 16,
        title: "The Ledge",
        image: "img/TheLedge2011.jpeg",
        production: 2011,
        rating: "7.5",
        duration: "2mins 29secs",
        description: "The Ledge description",
        category: "",
        categoryCri: "Crime",
        categoryDoc: "",
        categoryDra: "Drama",
        categoryBio: "",
        categorySci: "",
        categoryFan: "Fantasy",
        categoryAdv: "",
        categoryHor: "",
        categoryNSFW: "",
        categoryAni: "",
        categoryWes: "",
        categoryRom: "Romance",
        video: "vid/TheCuriousCaseOfBenjaminButton.MP4",
        playVideo: () => { videos.src = "vid/TheCuriousCaseOfBenjaminButton.MP4";
            myVideo.style.display= "block"; videos.play();
        }
    },
    {
        id: 17,
        title: "300",
        image: "img/300-2006.jpeg",
        production: 2006,
        rating: "9.0",
        duration: "2mins 29secs",
        description: "300 description",
        category: "Action",
        categoryCri: "",
        categoryDoc: "Documentary",
        categoryDra: "Drama",
        categoryBio: "",
        categorySci: "SciFi",
        categoryFan: "Fantasy",
        categoryAdv: "Adventure",
        categoryHor: "",
        categoryNSFW: "",
        categoryAni: "",
        categoryWes: "",
        categoryRom: "",
        video: "vid/TheCuriousCaseOfBenjaminButton.MP4",
        playVideo: () => { videos.src = "vid/TheCuriousCaseOfBenjaminButton.MP4";
            myVideo.style.display= "block"; videos.play();
        }
    },
    {
        id: 18,
        title: "300: Rise of an empire",
        image: "img/300-riseOfanEmpire2014.jpg",
        production: 2014,
        rating: "8.0",
        duration: "2mins 29secs",
        description: "300: Rise of an empire description",
        category: "Action",
        categoryCri: "",
        categoryDoc: "Documentary",
        categoryDra: "Drama",
        categoryBio: "",
        categorySci: "SciFi",
        categoryFan: "Fantasy",
        categoryAdv: "Adventure",
        categoryHor: "",
        categoryNSFW: "",
        categoryAni: "",
        categoryWes: "",
        categoryRom: "",
        video: "vid/TheCuriousCaseOfBenjaminButton.MP4",
        playVideo: () => { videos.src = "vid/TheCuriousCaseOfBenjaminButton.MP4";
            myVideo.style.display= "block"; videos.play();
        }
    },
    {
        id: 19,
        title: "Devotion",
        image: "img/Devotion2022.jpg",
        production: 2022,
        rating: "8.0",
        duration: "2mins 29secs",
        description: "Devotion description",
        category: "Action",
        categoryCri: "",
        categoryDoc: "Documentary",
        categoryDra: "Drama",
        categoryBio: "Biography",
        categorySci: "",
        categoryFan: "",
        categoryAdv: "Adventure",
        categoryHor: "",
        categoryNSFW: "",
        categoryAni: "",
        categoryWes: "",
        categoryRom: "",
        video: "vid/TheCuriousCaseOfBenjaminButton.MP4",
        playVideo: () => { videos.src = "vid/TheCuriousCaseOfBenjaminButton.MP4";
            myVideo.style.display= "block"; videos.play();
        }
    },
    {
        id: 20,
        title: "Nuremberg",
        image: "img/nuremberg2000.jpeg",
        production: 2000,
        rating: "9.0",
        duration: "2mins 29secs",
        description: "Nuremberg description",
        category: "",
        categoryCri: "Crime",
        categoryDoc: "Documentary",
        categoryDra: "Drama",
        categoryBio: "Biography",
        categorySci: "",
        categoryFan: "",
        categoryAdv: "",
        categoryHor: "",
        categoryNSFW: "",
        categoryAni: "",
        categoryWes: "",
        categoryWes: "",
        video: "vid/TheCuriousCaseOfBenjaminButton.MP4",
        playVideo: () => { videos.src = "vid/TheCuriousCaseOfBenjaminButton.MP4";
            myVideo.style.display= "block"; videos.play();
        }
    },
    {
        id: 21,
        title: "Dances with wolves",
        image: "img/dancesWithWolves.jpeg",
        production: 1990,
        rating: "8.0",
        duration: "2mins 29secs",
        description: "Dances with wolves description",
        category: "Action",
        categoryCri: "Crime",
        categoryDoc: "Documentary",
        categoryDra: "Drama",
        categoryBio: "",
        categorySci: "",
        categoryFan: "",
        categoryAdv: "Adventure",
        categoryHor: "",
        categoryNSFW: "",
        categoryAni: "",
        categoryWes: "Western",
        categoryRom: "",
        video: "vid/TheCuriousCaseOfBenjaminButton.MP4",
        playVideo: () => { videos.src = "vid/TheCuriousCaseOfBenjaminButton.MP4";
            myVideo.style.display= "block"; videos.play();
        }
    },
    {
        id: 22,
        title: "Ray Charles",
        image: "img/Ray-Charles2004.jpg",
        production: 2004,
        rating: "9.0",
        duration: "2mins 29secs",
        description: "Ray Charles description",
        category: "",
        categoryCri: "",
        categoryDoc: "Documentary",
        categoryDra: "Drama",
        categoryBio: "Biography",
        categorySci: "",
        categoryFan: "",
        categoryAdv: "Adventure",
        categoryHor: "",
        categoryNSFW: "",
        categoryAni: "",
        categoryWes: "",
        categoryRom: "Romance",
        video: "vid/TheCuriousCaseOfBenjaminButton.MP4",
        playVideo: () => { videos.src = "vid/TheCuriousCaseOfBenjaminButton.MP4";
            myVideo.style.display= "block"; videos.play();
        }
    },
    {
        id: 23,
        title: "GoodFellas",
        image: "img/goodFellas1990.jpg",
        production: 1990,
        rating: "8.0",
        duration: "2mins 29secs",
        description: "GoodFellas description",
        category: "Action",
        categoryCri: "Crime",
        categoryDoc: "",
        categoryDra: "Drama",
        categoryBio: "",
        categorySci: "",
        categoryFan: "Fantasy",
        categoryAdv: "",
        categoryHor: "",
        categoryNSFW: "",
        categoryAni: "",
        categoryWes: "",
        categoryRom: "",
        video: "vid/TheCuriousCaseOfBenjaminButton.MP4",
        playVideo: () => { videos.src = "vid/TheCuriousCaseOfBenjaminButton.MP4";
            myVideo.style.display= "block"; videos.play();
        }
    },
    {
        id: 24,
        title: "Shawshank Redemption",
        image: "img/shawshankRedemption1994.jpg",
        production: 1994,
        rating: "8.5",
        duration: "2mins 29secs",
        description: "Shawshank Redemption description",
        category: "",
        categoryCri: "Crime",
        categoryDoc: "",
        categoryDra: "Drama",
        categoryBio: "",
        categorySci: "",
        categoryFan: "Fantasy",
        categoryAdv: "Adventure",
        categoryHor: "",
        categoryNSFW: "",
        categoryAni: "",
        categoryWes: "",
        categoryRom: "",
        video: "vid/TheCuriousCaseOfBenjaminButton.MP4",
        playVideo: () => { videos.src = "vid/TheCuriousCaseOfBenjaminButton.MP4";
            myVideo.style.display= "block"; videos.play();
        }
    },
    {
        id: 25,
        title: "Ex Machina",
        image: "img/ex-mchina2014.webp",
        production: 2014,
        rating: "8.0",
        duration: "2mins 29secs",
        description: "Ex Machina description",
        category: "",
        categoryCri: "Crime",
        categoryDoc: "",
        categoryDra: "Drama",
        categoryBio: "",
        categorySci: "SciFi",
        categoryFan: "Fantasy",
        categoryAdv: "Adventure",
        categoryHor: "",
        categoryNSFW: "",
        categoryAni: "",
        categoryWes: "",
        categoryRom: "Romance",
        video: "vid/TheCuriousCaseOfBenjaminButton.MP4",
        playVideo: () => { videos.src = "vid/TheCuriousCaseOfBenjaminButton.MP4";
            myVideo.style.display= "block"; videos.play();
        }
    },
    {
        id: 26,
        title: "Once upon a time in hollywood",
        image: "img/once-upon-a-time-in-hollywood2019.jpg",
        production: 2019,
        rating: "8.0",
        duration: "2mins 29secs",
        description: "Once opon time in hollywood description",
        category: "Action",
        categoryCri: "Crime",
        categoryDoc: "",
        categoryDra: "Drama",
        categoryBio: "",
        categorySci: "",
        categoryFan: "Fantasy",
        categoryAdv: "Adventure",
        categoryHor: "",
        categoryNSFW: "",
        categoryAni: "",
        categoryWes: "",
        categoryRom: "",
        video: "vid/TheCuriousCaseOfBenjaminButton.MP4",
        playVideo: () => { videos.src = "vid/TheCuriousCaseOfBenjaminButton.MP4";
            myVideo.style.display= "block"; videos.play();
        }
    },
    {
        id: 27,
        title: "The shape of water",
        image: "img/theShapeOfWater2017.jpeg",
        production: 2017,
        rating: "8.5",
        duration: "2mins 29secs",
        description: "The shape of water description",
        category: "",
        categoryCri: "",
        categoryDoc: "",
        categoryDra: "Drama",
        categoryBio: "",
        categorySci: "SciFi",
        categoryFan: "Fantasy",
        categoryAdv: "",
        categoryHor: "",
        categoryNSFW: "",
        categoryAni: "",
        categoryWes: "",
        categoryRom: "Romance",
        video: "vid/TheCuriousCaseOfBenjaminButton.MP4",
        playVideo: () => { videos.src = "vid/TheCuriousCaseOfBenjaminButton.MP4";
            myVideo.style.display= "block"; videos.play();
        }
    },
    {
        id: 28,
        title: "Selma",
        image: "img/Selma2014.jpg",
        production: 2014,
        rating: "8.0",
        duration: "2mins 29secs",
        description: "Selma description",
        category: "Action",
        categoryCri: "Crime",
        categoryDoc: "Documentary",
        categoryDra: "Drama",
        categoryBio: "Biography",
        categorySci: "",
        categoryFan: "",
        categoryAdv: "",
        categoryHor: "",
        categoryNSFW: "",
        categoryAni: "",
        categoryWes: "",
        categoryRom: "",
        video: "vid/TheCuriousCaseOfBenjaminButton.MP4",
        playVideo: () => { videos.src = "vid/TheCuriousCaseOfBenjaminButton.MP4";
            myVideo.style.display= "block"; videos.play();
        }
    },
    {
        id: 29,
        title: "The Great Gatsby",
        image: "img/theGreatGatsby2013.png",
        production: 2013,
        rating: "8.0",
        duration: "2mins 29secs",
        description: "The Great Gatsby description",
        category: "",
        categoryCri: "Crime",
        categoryDoc: "",
        categoryDra: "Drama",
        categoryBio: "",
        categorySci: "",
        categoryFan: "Fantasy",
        categoryAdv: "Adventure",
        categoryHor: "",
        categoryNSFW: "",
        categoryAni: "",
        categoryWes: "",
        categoryRom: "Romance",
        video: "vid/TheCuriousCaseOfBenjaminButton.MP4",
        playVideo: () => { videos.src = "vid/TheCuriousCaseOfBenjaminButton.MP4";
            myVideo.style.display= "block"; videos.play();
        }
    },
    {
        id: 30,
        title: "Dunkirk",
        image: "img/Dunkirk2017.jpg",
        production: 2017,
        rating: "8.0",
        duration: "2mins 29secs",
        description: "Dunkirk description",
        category: "Action",
        categoryCri: "Crime",
        categoryDoc: "Documentary",
        categoryDra: "Drama",
        categoryBio: "",
        categorySci: "",
        categoryFan: "",
        categoryAdv: "Adventure",
        categoryHor: "Horror",
        categoryNSFW: "",
        categoryAni: "",
        categoryWes: "",
        categoryRom: "",
        video: "vid/TheCuriousCaseOfBenjaminButton.MP4",
        playVideo: () => { videos.src = "vid/TheCuriousCaseOfBenjaminButton.MP4";
            myVideo.style.display= "block"; videos.play();
        }
    },
    {
        id: 31,
        title: "Catch me if you can",
        image: "img/catchMeIfYouCan2003.jpg",
        production: 2003,
        rating: "8.5",
        duration: "2mins 29secs",
        description: "Catch me if you can description",
        category: "",
        categoryCri: "Crime",
        categoryDoc: "",
        categoryDra: "Drama",
        categoryBio: "",
        categorySci: "",
        categoryFan: "Fantasy",
        categoryAdv: "Adventure",
        categoryHor: "",
        categoryNSFW: "",
        categoryAni: "",
        categoryWes: "",
        categoryRom: "",
        video: "vid/TheCuriousCaseOfBenjaminButton.MP4",
        playVideo: () => { videos.src = "vid/TheCuriousCaseOfBenjaminButton.MP4";
            myVideo.style.display= "block"; videos.play();
        }
    },
    {
        id: 32,
        title: "Django Unchained",
        image: "img/Django-unchained2012.jpg",
        production: 2012,
        rating: "9.0",
        duration: "2mins 29secs",
        description: "Django Unchained description",
        category: "Action",
        categoryCri: "Crime",
        categoryDoc: "",
        categoryDra: "Drama",
        categoryBio: "",
        categorySci: "",
        categoryFan: "Fantasy",
        categoryAdv: "Adventure",
        categoryHor: "",
        categoryNSFW: "",
        categoryAni: "",
        categoryWes: "Western",
        categoryRom: "Romance",
        video: "vid/TheCuriousCaseOfBenjaminButton.MP4",
        playVideo: () => { videos.src = "vid/TheCuriousCaseOfBenjaminButton.MP4";
            myVideo.style.display= "block"; videos.play();
        }
    },
    {
        id: 33,
        title: "Get Out",
        image: "img/getOut2017.jpeg",
        production: 2017,
        rating: "8.0",
        duration: "2mins 29secs",
        description: "Get Out description",
        category: "",
        categoryCri: "Crime",
        categoryDoc: "",
        categoryDra: "Drama",
        categoryBio: "",
        categorySci: "",
        categoryFan: "Fantasy",
        categoryAdv: "Adventure",
        categoryHor: "Horror",
        categoryNSFW: "NSFW",
        categoryAni: "",
        categoryWes: "",
        categoryRom: "Romance",
        video: "vid/TheCuriousCaseOfBenjaminButton.MP4",
        playVideo: () => { videos.src = "vid/TheCuriousCaseOfBenjaminButton.MP4";
            myVideo.style.display= "block"; videos.play();
        }
    },
    {
        id: 34,
        title: "Gone Girl",
        image: "img/gone-girl2014.jpeg",
        production: 2014,
        rating: "8.0",
        duration: "2mins 29secs",
        description: "Gone Girl description",
        category: "",
        categoryCri: "Crime",
        categoryDoc: "",
        categoryDra: "Drama",
        categoryBio: "",
        categorySci: "",
        categoryFan: "Fantasy",
        categoryAdv: "Adventure",
        categoryHor: "",
        categoryNSFW: "",
        categoryAni: "",
        categoryWes: "",
        categoryRom: "",
        video: "vid/TheCuriousCaseOfBenjaminButton.MP4",
        playVideo: () => { videos.src = "vid/TheCuriousCaseOfBenjaminButton.MP4";
            myVideo.style.display= "block"; videos.play();
        }
    },
    {
        id: 35,
        title: "The Revenant",
        image: "img/theRevenant2015.jpg",
        production: 2015,
        rating: "8.0",
        duration: "2mins 29secs",
        description: "The Revenant description",
        category: "Action",
        categoryCri: "Crime",
        categoryDoc: "",
        categoryDra: "Drama",
        categoryBio: "",
        categorySci: "",
        categoryFan: "Fantasy",
        categoryAdv: "Adventure",
        categoryHor: "",
        categoryNSFW: "",
        categoryAni: "",
        categoryWes: "",
        categoryRom: "",
        video: "vid/TheCuriousCaseOfBenjaminButton.MP4",
        playVideo: () => { videos.src = "vid/TheCuriousCaseOfBenjaminButton.MP4";
            myVideo.style.display= "block"; videos.play();
        }
    },
    {
        id: 36,
        title: "The Social Network",
        image: "img/theSocialNetwork.jpeg",
        production: 2010,
        rating: "7.5",
        duration: "2mins 29secs",
        description: "Social Network description",
        category: "",
        categoryCri: "",
        categoryDoc: "Documentary",
        categoryDra: "Drama",
        categoryBio: "Biography",
        categorySci: "",
        categoryFan: "",
        categoryAdv: "",
        categoryHor: "",
        categoryNSFW: "",
        categoryAni: "",
        categoryWes: "",
        categoryRom: "",
        video: "vid/TheCuriousCaseOfBenjaminButton.MP4",
        playVideo: () => { videos.src = "vid/TheCuriousCaseOfBenjaminButton.MP4";
            myVideo.style.display= "block"; videos.play();
        }
    },
];
